// GENERATED by redstars-studio — the AppPlugin the host loads. Pure no-code:
// primitive slots only. For custom logic/modals, edit this repo directly.
import type { AppPlugin } from '@delminator/core-ui'
import { collaboratorView } from './collaborator/menu'
import { strings } from './i18n'

const plugin: AppPlugin = {
  id: 'studio',
  name: {"fr":"Studio","en":"Studio"},
  icon: "🛠️",
  // Console/Minitel: an ASCII icon — the web emoji folds to a blank in Videotex G0.
  console: { icon: 'camera', iconGrid: '16x12:////////////////////////////a7xqamq8vGpqav////9qampqav9oampq/2ho//9qampqamr/aGpqampqav9ovWhoapSVlWpoampqamr/aGhqav+UlZVqamhoaP////9oaP//amiVlZX///////////9qampqVpWVlf////////9qvWpqav+VlZWVlf///2pqampqav///5WVlZWV//9qampqav//////lZWVlZX//2pqav//////////lZWV' },
  version: '0.1.9',
  minCoreVersion: '0.6.0',
  accentToken: 'c-accent',
  views: {
    collaborator: collaboratorView,
  },
  strings,
}

export default plugin
