// GENERATED by redstars-studio — the AppPlugin the host loads. Pure no-code:
// primitive slots only. For custom logic/modals, edit this repo directly.
import type { AppPlugin } from '@delminator/core-ui'
import { collaboratorView } from './collaborator/menu'
import { strings } from './i18n'

const plugin: AppPlugin = {
  id: 'studio',
  name: {"fr":"Studio","en":"Studio"},
  icon: "🛠️",
  // Console/Minitel: an ASCII icon — the web emoji folds to a blank in Videotex G0.
  console: { icon: '[o]' },
  version: '0.1.7',
  minCoreVersion: '0.6.0',
  accentToken: 'c-accent',
  views: {
    collaborator: collaboratorView,
  },
  strings,
}

export default plugin
