#!/usr/bin/env node
// RedStars app codegen — spec → a complete app repo (from redstars-app-template).
//   node generate.mjs <spec.json> [outDir]
// Default outDir = ../../../redstars-<id> (sibling of the template).
//
// Strategy: copy the template tree, substitute the `myapp`/`3010` tokens, then
// OVERWRITE the spec-driven files (plugin.ts, view menus, i18n, appmeta, the pod
// main.go/crud.go) and emit migrations for declared entities. Pure no-code apps:
// primitive slots only (no custom React) — the eject boundary is "edit the repo".
import { readFileSync, writeFileSync, cpSync, rmSync, mkdirSync, existsSync, readdirSync, statSync, renameSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
// Env overrides let the CI "App Factory" point at a checked-out template + out dir.
const TEMPLATE = process.env.RS_TEMPLATE || join(HERE, '..', '..', '..', 'redstars-app-template')
const RED = process.env.RS_OUTROOT || join(HERE, '..', '..', '..')   // ~/red (out parent)
const PUBKEY = 'RWREK3zpB9JizufC0rKjizmv8K+KbjLgo9OXKt7tv8jtbQM0itTMfA8B'

const specPath = process.argv[2]
if (!specPath) { console.error('usage: node generate.mjs <spec.json> [outDir]'); process.exit(1) }
const spec = JSON.parse(readFileSync(specPath, 'utf8'))
const id = spec.id
if (!/^[a-z][a-z0-9]{2,20}$/.test(id || '')) { console.error('bad id:', id); process.exit(1) }
const out = process.argv[3] || join(RED, `redstars-${id}`)
const port = String(spec.port || 3014)

// ---------- helpers ----------------------------------------------------------
const j = (o, ind = 0) => JSON.stringify(o, null, 2).replace(/\n/g, '\n' + ' '.repeat(ind))
const loc = (o) => JSON.stringify(o)
const isText = (p) => /\.(go|ts|tsx|json|ya?ml|md|npmrc|gitignore|mod|sum)$|Dockerfile$/.test(p)
function walk(dir, fn) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (['node_modules', '.git', 'dist'].includes(e)) continue
    if (statSync(p).isDirectory()) walk(p, fn); else fn(p)
  }
}

// ---------- 1. copy template (minus heavy/vcs dirs) --------------------------
if (existsSync(out)) { console.error('outDir exists, refusing:', out); process.exit(1) }
cpSync(TEMPLATE, out, { recursive: true, filter: (src) => !/(^|\/)(node_modules|\.git|dist)(\/|$)/.test(src) })
renameSync(join(out, 'cmd', 'myapp'), join(out, 'cmd', id))

// ---------- 2. token substitution -------------------------------------------
walk(out, (p) => {
  if (!isText(p)) return
  let s = readFileSync(p, 'utf8')
  const t = s.replaceAll('myapp', id).replaceAll('3010', port)
  if (t !== s) writeFileSync(p, t)
})
// rename files whose basename carries the `myapp` token (e.g. infra/myapp.yaml)
walk(out, (p) => {
  const b = basename(p)
  if (b.includes('myapp')) renameSync(p, join(dirname(p), b.replaceAll('myapp', id)))
})

// ---------- 3. drop bespoke (custom-React) dirs — pure-data app -------------
// Whole view dirs go too (orphan template menu.ts would import deleted files);
// step 4 recreates only the roles the spec declares.
for (const d of ['modales', 'tabs', 'parametres', 'taches', 'db', 'collaborator', 'admin', 'user'])
  rmSync(join(out, 'ui', 'src', d), { recursive: true, force: true })

// ---------- 4. regenerate spec-driven UI ------------------------------------
const accent = spec.accentToken || 'c-accent'
const views = spec.views || {}
const viewVar = { collaborator: 'collaboratorView', admin: 'adminView', user: 'userView' }
for (const [role, view] of Object.entries(views)) {
  const menu = (view.menu || []).map(m => {
    const e = { id: m.id, label: m.label }
    if (m.icon) e.icon = m.icon
    if (m.align) e.align = m.align
    return e
  })
  const slots = {}
  for (const m of view.menu || []) slots[m.id] = m.slot
  const body = `import type { PluginView } from '@delminator/core-ui'

// GENERATED by redstars-studio from app.spec.json — edit the spec, not this file
// (regenerating overwrites it). Cast bypasses the published core-ui type lag for
// newer primitives (collection/settings/tasks/dashboard/announcements).
export const ${viewVar[role]} = {
  menu: ${j(menu, 2)},
  slots: ${j(slots, 2)},
} as unknown as PluginView
`
  mkdirSync(join(out, 'ui', 'src', role), { recursive: true })
  writeFileSync(join(out, 'ui', 'src', role, 'menu.ts'), body)
}

// plugin.ts (pure data — no modals/tabs/custom components)
const imports = Object.keys(views).map(r => `import { ${viewVar[r]} } from './${r}/menu'`).join('\n')
const viewLines = Object.keys(views).map(r => `    ${r}: ${viewVar[r]},`).join('\n')
writeFileSync(join(out, 'ui', 'src', 'plugin.ts'), `// GENERATED by redstars-studio — the AppPlugin the host loads. Pure no-code:
// primitive slots only. For custom logic/modals, edit this repo directly.
import type { AppPlugin } from '@delminator/core-ui'
${imports}
import { strings } from './i18n'

const plugin: AppPlugin = {
  id: '${id}',
  name: ${loc(spec.name)},
  icon: ${JSON.stringify(spec.icon || '🧩')},
  version: '${spec.version || '0.1.0'}',
  minCoreVersion: '${spec.minCoreVersion || '0.6.0'}',
  accentToken: '${accent}',
  views: {
${viewLines}
  },
  strings,
}

export default plugin
`)

// i18n (empty — primitives carry their own localized labels)
writeFileSync(join(out, 'ui', 'src', 'i18n.ts'), `// GENERATED — primitive slots carry their own labels; add app strings here.
export const strings = { fr: {} as Record<string, string>, en: {} as Record<string, string> }
`)

// ---------- 5. appmeta.json --------------------------------------------------
writeFileSync(join(out, 'cmd', id, 'appmeta.json'), JSON.stringify({
  id, name: spec.name?.fr || id, icon: spec.icon || '🧩', color: spec.color || '#6366f1',
  description: spec.description || '', visibility: spec.visibility || 'public',
}, null, 2) + '\n')

// ---------- 6. pod main.go + crud.go ----------------------------------------
const entities = spec.entities || []
const tbl = (n) => `${id}_${n}`
const routes = []
for (const e of entities) {
  routes.push(`\t\tregisterCRUD(api, "/${e.name}", "${tbl(e.name)}")`)
  if (e.kind === 'announcements' || e.publishable)
    routes.push(`\t\tapi.POST("/${e.name}/:id/publish", publishHandler("${tbl(e.name)}"))`)
}
writeFileSync(join(out, 'cmd', id, 'main.go'), `// GENERATED by redstars-studio. App pod: serves the signed UI bundle (pluginhost)
// + /api/v1/${id}/* generic CRUD over the org DB via the Core SDK. No direct DB.
package main

import (
\t"context"
\t_ "embed"
\t"log"
\t"net/http"
\t"os"
\t"runtime"
\t"time"

\t"github.com/delminator/redstars/backend/pkg/pluginhost"
\t"github.com/delminator/redstars/backend/pkg/coresdk"
\t"github.com/gin-gonic/gin"
)

// SHARED org plugin-signing pubkey — identical in every app + the frontend.
const pluginPubkey = "${PUBKEY}"

//go:embed ui-fallback/plugin.js
var fallbackBundle []byte

//go:embed ui-fallback/plugin.js.minisig
var fallbackSignature []byte

//go:embed ui-fallback/manifest.json
var fallbackManifest []byte

//go:embed appmeta.json
var appMeta []byte

var core *coresdk.Client

func main() {
\tlog.Println("Starting ${id} service (app mode)...")
\tcore = coresdk.NewClient(getEnv("CORE_SERVICE_URL", "http://core:3000"), "${id}", os.Getenv("INTERNAL_API_KEY"))

\tgin.SetMode(gin.ReleaseMode)
\trouter := gin.New()
\trouter.Use(gin.Recovery(), gin.Logger())
\trouter.SetTrustedProxies([]string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"})

\trouter.GET("/health", func(c *gin.Context) {
\t\tc.JSON(http.StatusOK, gin.H{"service": "${id}", "mode": "app", "status": "healthy", "timestamp": time.Now().Unix(), "go_version": runtime.Version()})
\t})

\tpluginHost := pluginhost.New(pluginhost.Config{
\t\tAppID: "${id}", GHRepo: "delminator/redstars-${id}", Pubkey: pluginPubkey,
\t\tEmbedBundle: fallbackBundle, EmbedSignature: fallbackSignature, EmbedManifest: fallbackManifest, EmbedMeta: appMeta,
\t})
\tif err := pluginHost.Boot(context.Background()); err != nil {
\t\tlog.Printf("[pluginhost] boot failed (continuing with fallback): %v", err)
\t}

\tapi := router.Group("/api/v1/${id}")
\t{
\t\tui := api.Group("/ui")
\t\tpluginHost.RegisterRoutes(ui)
\t\tui.GET("/config", handleUIConfig)
\t\tinternal := api.Group("/internal/ui")
\t\tpluginHost.RegisterInternalRoutes(internal)

\t\t// --- generated resource routes (declared entities) ---
${routes.join('\n') || '\t\t_ = api'}
\t}

\tport := getEnv("PORT", "${port}")
\tlog.Printf("${id} listening on :%s", port)
\tif err := router.Run(":" + port); err != nil {
\t\tlog.Fatal(err)
\t}
}
`)

writeFileSync(join(out, 'cmd', id, 'crud.go'), `// GENERATED — generic CRUD helpers over core's org-DB API (the canonical pattern).
package main

import (
\t"net/http"
\t"net/url"
\t"strings"
\t"time"

\t"github.com/delminator/redstars/backend/pkg/coresdk"
\t"github.com/gin-gonic/gin"
)

func reqCtx(c *gin.Context) coresdk.RequestContext {
\ttoken := c.GetHeader("Authorization")
\tif strings.HasPrefix(token, "Bearer ") {
\t\ttoken = strings.TrimPrefix(token, "Bearer ")
\t}
\treturn coresdk.RequestContext{AuthToken: token, OrgOID: c.GetHeader("X-Organization-OID")}
}

func getEnv(key, fallback string) string {
\tif v := os.Getenv(key); v != "" {
\t\treturn v
\t}
\treturn fallback
}

// filterableQuery maps plain ?status=/?type= params onto core's filter_<col>.
var filterableQuery = map[string]bool{"status": true, "type": true, "kind": true, "category": true, "parent_id": true}

func crudList(table string) gin.HandlerFunc {
\treturn func(c *gin.Context) {
\t\tparams := url.Values{}
\t\tif l := c.Query("limit"); l != "" {
\t\t\tparams.Set("limit", l)
\t\t}
\t\tif o := c.Query("offset"); o != "" {
\t\t\tparams.Set("offset", o)
\t\t}
\t\tif s := c.Query("sort"); s != "" {
\t\t\tparams.Set("sort", s)
\t\t}
\t\tfor k, v := range c.Request.URL.Query() {
\t\t\tif strings.HasPrefix(k, "filter_") {
\t\t\t\tparams.Set(k, v[0])
\t\t\t}
\t\t\tif filterableQuery[k] {
\t\t\t\tparams.Set("filter_"+k, v[0])
\t\t\t}
\t\t}
\t\tr, err := core.ListRows(reqCtx(c), table, params)
\t\tif err != nil {
\t\t\tc.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
\t\t\treturn
\t\t}
\t\tc.JSON(http.StatusOK, r)
\t}
}

func crudGet(table string) gin.HandlerFunc {
\treturn func(c *gin.Context) {
\t\tr, err := core.GetRow(reqCtx(c), table, c.Param("id"))
\t\tif err != nil {
\t\t\tc.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
\t\t\treturn
\t\t}
\t\tc.JSON(http.StatusOK, r)
\t}
}

func crudCreate(table string) gin.HandlerFunc {
\treturn func(c *gin.Context) {
\t\tvar data map[string]interface{}
\t\tif err := c.ShouldBindJSON(&data); err != nil {
\t\t\tc.JSON(http.StatusBadRequest, gin.H{"error": "Invalid JSON"})
\t\t\treturn
\t\t}
\t\tid, err := core.InsertRow(reqCtx(c), table, data)
\t\tif err != nil {
\t\t\tc.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
\t\t\treturn
\t\t}
\t\tc.JSON(http.StatusCreated, gin.H{"id": id})
\t}
}

func crudUpdate(table string) gin.HandlerFunc {
\treturn func(c *gin.Context) {
\t\tvar data map[string]interface{}
\t\tif err := c.ShouldBindJSON(&data); err != nil {
\t\t\tc.JSON(http.StatusBadRequest, gin.H{"error": "Invalid JSON"})
\t\t\treturn
\t\t}
\t\tif err := core.UpdateRow(reqCtx(c), table, c.Param("id"), data); err != nil {
\t\t\tc.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
\t\t\treturn
\t\t}
\t\tc.JSON(http.StatusOK, gin.H{"updated": true})
\t}
}

func crudDelete(table string) gin.HandlerFunc {
\treturn func(c *gin.Context) {
\t\tif err := core.DeleteRow(reqCtx(c), table, c.Param("id")); err != nil {
\t\t\tc.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
\t\t\treturn
\t\t}
\t\tc.JSON(http.StatusOK, gin.H{"deleted": true})
\t}
}

func registerCRUD(g *gin.RouterGroup, path, table string) {
\tg.GET(path, crudList(table))
\tg.GET(path+"/:id", crudGet(table))
\tg.POST(path, crudCreate(table))
\tg.PUT(path+"/:id", crudUpdate(table))
\tg.DELETE(path+"/:id", crudDelete(table))
}

// publishHandler marks a row published (status + date set server-side).
func publishHandler(table string) gin.HandlerFunc {
\treturn func(c *gin.Context) {
\t\tdata := map[string]interface{}{"status": "published", "published_at": time.Now().Format(time.RFC3339)}
\t\tif err := core.UpdateRow(reqCtx(c), table, c.Param("id"), data); err != nil {
\t\t\tc.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
\t\t\treturn
\t\t}
\t\tc.JSON(http.StatusOK, gin.H{"updated": true})
\t}
}
`)

// crud.go uses os via getEnv → ensure import. (kept separate to keep main.go lean)
let crud = readFileSync(join(out, 'cmd', id, 'crud.go'), 'utf8').replace('\t"net/http"', '\t"net/http"\n\t"os"')
writeFileSync(join(out, 'cmd', id, 'crud.go'), crud)

// ---------- 6b. self-contained deploy workflow (eau-pattern) ----------------
// Overwrite the template's core-curl deploy with a self-contained one: applies
// the LOCAL infra manifest (no fleet-risky core push) and creates <id>-secret
// with the shared INTERNAL_API_KEY (the gotcha that 500'd eau).
writeFileSync(join(out, '.github', 'workflows', 'deploy-dev.yml'), `name: Deploy ${id} Service (Dev)
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: delminator/redstars-${id}/${id}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Checkout backend (build dependency)
        uses: actions/checkout@v4
        with:
          repository: delminator/redstars-core
          token: \${{ secrets.CORE_REPO_TOKEN }}
          path: backend
          sparse-checkout: apps/backend
      - name: Prepare build context
        run: |
          mkdir -p /tmp/ctx/${id} /tmp/ctx/backend
          rsync -a --exclude=ui --exclude=node_modules --exclude=.git . /tmp/ctx/${id}/
          cp -r backend/apps/backend/* /tmp/ctx/backend/
      - name: Refresh ui-fallback from latest plugin release
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          dest=/tmp/ctx/${id}/cmd/${id}/ui-fallback
          short="\${GITHUB_SHA::7}"
          bp=\$(gh run list --workflow='Build Plugin (ui)' --commit=\${{ github.sha }} --json databaseId --jq 'length' 2>/dev/null || echo 0)
          tag=""
          if [ "\$bp" != "0" ] && [ "\$bp" != "" ]; then
            for i in \$(seq 1 30); do
              tag=\$(gh release list --repo \${{ github.repository }} --limit 50 --json tagName --jq '.[].tagName' | grep '^plugin-v' | grep -- "-\${short}\$" | head -1 || true)
              [ -n "\$tag" ] && break
              echo "waiting for build-plugin release of \${short} (\$i/30)…"; sleep 10
            done
          fi
          if [ -z "\$tag" ]; then
            tag=\$(gh release list --repo \${{ github.repository }} --limit 50 --json tagName --jq '.[].tagName' | grep '^plugin-v' | head -1 || true)
          fi
          if [ -z "\$tag" ]; then echo "No plugin-v* release yet — keeping placeholder."; exit 0; fi
          echo "Refreshing ui-fallback from \$tag"; mkdir -p "\$dest" && cd "\$dest"
          gh release download "\$tag" --repo \${{ github.repository }} --pattern 'plugin.js' --pattern 'plugin.js.minisig' --pattern 'manifest.json' --clobber
          base="https://api.dev.redstars.redlinks.fr/api/v1/${id}/ui"
          jq --arg bu "\$base/plugin.js" --arg su "\$base/plugin.js.minisig" '. + {bundle_url: \$bu, signature_url: \$su, min_core_version: "0.6.0", roles: ["collaborator","admin","user"]}' manifest.json > manifest.json.new
          mv manifest.json.new manifest.json
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: \${{ env.REGISTRY }}
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: /tmp/ctx
          file: ./Dockerfile
          push: true
          tags: \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:\${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy (self-contained — local manifest + secret)
        run: |
          echo "\${{ secrets.KUBECONFIG }}" | base64 -d > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig
          IMAGE=\${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:\${{ github.sha }}
          KEY=\$(kubectl -n redstars-dev get secret eau-secret -o jsonpath='{.data.INTERNAL_API_KEY}' | base64 -d)
          kubectl -n redstars-dev create secret generic ${id}-secret --from-literal=INTERNAL_API_KEY="\$KEY" --dry-run=client -o yaml | kubectl apply -f -
          sed "s|\${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:latest|\$IMAGE|" infra/${id}.yaml | kubectl apply -f -
          kubectl apply -f infra/${id}-ingressroute.yaml
          kubectl apply -f infra/${id}-network-policy.yaml
          # add to core's ingress allowlist (idempotent) so /internal calls pass
          kubectl -n redstars-dev patch networkpolicy core-allow-ingress --type=json \\
            -p="[{\\"op\\":\\"add\\",\\"path\\":\\"/spec/ingress/0/from/0/podSelector/matchExpressions/0/values/-\\",\\"value\\":\\"${id}\\"}]" 2>/dev/null || true
          kubectl -n redstars-dev rollout restart deployment/${id}
          kubectl -n redstars-dev rollout status deployment/${id} --timeout=180s
          rm /tmp/kubeconfig
`)

// ---------- 7. migrations (→ core repo pkg/database/sql/templates/<id>/) -----
const migDir = join(out, 'migrations', id)
mkdirSync(migDir, { recursive: true })
const sqlType = (f) => ({ text: 'TEXT', number: 'NUMERIC', date: 'DATE', bool: 'BOOLEAN', enum: 'TEXT' }[f.type] || 'TEXT')
function fieldLine(f) {
  let line = `    ${f.name} ${sqlType(f)}`
  if (f.type === 'bool') line += ' DEFAULT false'
  else if (f.type === 'text') line += (f.required ? ' NOT NULL' : '') + " DEFAULT ''"
  else if (f.required) line += ' NOT NULL'
  if (f.type === 'enum' && f.options?.length) line += ` CHECK (${f.name} IN (${f.options.map(o => `'${o}'`).join(', ')}))`
  if (f.default !== undefined && f.type !== 'bool') line += ` DEFAULT '${f.default}'`
  return line
}
entities.forEach((e, i) => {
  const n = tbl(e.name)
  const seq = String(i + 1).padStart(3, '0')
  let sql
  if (e.kind === 'announcements') {
    sql = `CREATE TABLE IF NOT EXISTS ${n} (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    priority INTEGER DEFAULT 0,
    created_by_name TEXT DEFAULT '',
    image_url TEXT DEFAULT '',
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);`
  } else {
    const lines = (e.fields || []).map(fieldLine)
    if (e.publishable) {
      lines.push("    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived'))")
      lines.push('    published_at TIMESTAMP')
    }
    lines.push('    created_at TIMESTAMP NOT NULL DEFAULT NOW()')
    sql = `CREATE TABLE IF NOT EXISTS ${n} (\n    id SERIAL PRIMARY KEY,\n${lines.join(',\n')}\n);`
  }
  writeFileSync(join(migDir, `${seq}_${n}.sql`), `-- GENERATED by redstars-studio from app.spec.json\n${sql}\n`)
})

// ---------- 8. provenance ----------------------------------------------------
writeFileSync(join(out, 'app.spec.json'), JSON.stringify(spec, null, 2) + '\n')

console.log(`✓ generated ${id} → ${out}`)
console.log(`  entities: ${entities.map(e => e.name).join(', ') || '(none)'}`)
console.log(`  views: ${Object.keys(views).join(', ')}  port: ${port}`)
console.log(`  migrations → migrations/${id}/ (copy to core repo pkg/database/sql/templates/${id}/)`)
