// GENERATED by redstars-studio. App pod: serves the signed UI bundle (pluginhost)
// + /api/v1/studio/* generic CRUD over the org DB via the Core SDK. No direct DB.
package main

import (
	"context"
	_ "embed"
	"log"
	"net/http"
	"os"
	"runtime"
	"time"

	"github.com/delminator/redstars/backend/pkg/pluginhost"
	"github.com/delminator/redstars/backend/pkg/coresdk"
	"github.com/gin-gonic/gin"
)

// SHARED org plugin-signing pubkey — identical in every app + the frontend.
const pluginPubkey = "RWREK3zpB9JizufC0rKjizmv8K+KbjLgo9OXKt7tv8jtbQM0itTMfA8B"

//go:embed ui-fallback/plugin.js
var fallbackBundle []byte

//go:embed ui-fallback/plugin.js.minisig
var fallbackSignature []byte

//go:embed ui-fallback/manifest.json
var fallbackManifest []byte

//go:embed appmeta.json
var appMeta []byte

var core *coresdk.Client

func main() {
	log.Println("Starting studio service (app mode)...")
	core = coresdk.NewClient(getEnv("CORE_SERVICE_URL", "http://core:3000"), "studio", os.Getenv("INTERNAL_API_KEY"))

	gin.SetMode(gin.ReleaseMode)
	router := gin.New()
	router.Use(gin.Recovery(), gin.Logger())
	router.SetTrustedProxies([]string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"})

	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"service": "studio", "mode": "app", "status": "healthy", "timestamp": time.Now().Unix(), "go_version": runtime.Version()})
	})

	pluginHost := pluginhost.New(pluginhost.Config{
		AppID: "studio", GHRepo: "delminator/redstars-studio", Pubkey: pluginPubkey,
		EmbedBundle: fallbackBundle, EmbedSignature: fallbackSignature, EmbedManifest: fallbackManifest, EmbedMeta: appMeta,
	})
	if err := pluginHost.Boot(context.Background()); err != nil {
		log.Printf("[pluginhost] boot failed (continuing with fallback): %v", err)
	}

	api := router.Group("/api/v1/studio")
	{
		ui := api.Group("/ui")
		pluginHost.RegisterRoutes(ui)
		ui.GET("/config", handleUIConfig)
		internal := api.Group("/internal/ui")
		pluginHost.RegisterInternalRoutes(internal)

		// --- generated resource routes (declared entities) ---
		_ = api
	}

	port := getEnv("PORT", "3020")
	log.Printf("studio listening on :%s", port)
	if err := router.Run(":" + port); err != nil {
		log.Fatal(err)
	}
}
